### ISSUE TITLE
3개 랜덤 띄우기 - 도전01

### ISSUE THREAD

**Issue by jbeexxx** [ProjectInTheClass/mogrige#2]
let words1 = ["고양이", "노을", "의자", "분홍구름", "유리꽃병", "둥근테이블", "체크식탁보"]
        var resultSet = Set<String>()

        while resultSet.count < 3 {
            let randomIndext = Int(arc4random_uniform(UInt32(words1.count)))
            resultSet.insert(words1[randomIndext])
        }

        let _ = Array(resultSet)

        print(resultSet)

구글링 바닥까지 긁어서 발견한 구문입니다.
성공하긴 했는데 모르는 구문들이 많아서 문제입니다.

참고한 링크
https://stackoverflow.com/questions/45132047/randomly-select-5-elements-from-an-array-list-without-repeating-an-element

모르는 부분
1. 비어있는 Set을 지정한 이유 : **서로 다른 값을 중복 없이 저장하고자 할 때 사용하는 집단자료형 + 순서가 상관없음**
2. arc4random_uniform 구문 : **플러스 Int의 범위로 배열의 크기를 계산하고 그 번호를 랜덤인덱스로 참조하기 위한 구문**

더 쉬운 방법을 찾으신 분이 있다면 또 적어주세용

**Comment by thyomoon** [comment]
저는 아는거 짜집기 해서 요렇게 작성해봤습니다!

import Foundation

let keywordList = ["고양이", "강아지", "잠자리", "바람", "노을", "의자", "바다", "허수아비", "청소", "노트북", "책상", "손수건", "밀짚모자", "김밥", "옥수수", "코트", "패딩", "새싹", "봄비", "반딧불이", "토끼", "가을", "단풍", "산책", "손전등", "별", "하늘", "구름", "태풍", "손목시계", "책"]




func randomKeywordCombination(list: [String])-> Array<String> {
    var randomPickedKeywords = [String]()
    var selectionList = list
    
    while randomPickedKeywords.count < 3 {
        let randomInt = Int.random(in: 0...selectionList.count)
        
        randomPickedKeywords.append(list[randomInt])
        selectionList.remove(at: randomInt)
    }
    return randomPickedKeywords
}
