### ISSUE TITLE
02-2. 스와이프 액션과 데이터 (선택사항)

### ISSUE THREAD

**Issue by jbeexxx** [ProjectInTheClass/mogrige#6]
[02-1.데이터를 저장하는 방법 연구]가 수월하다면 진행해 봅니다. 

스와이프 액션으로 데이터를 다루는 방법에 대해 연구합니다. (예: 틴더) 

- REPICK, PICK, RETURN(다시보기) 총 3가지의 기능을 접목
- 기능과 스와이프의 방향이 은유적으로 잘 맞도록

**Comment by Huride** [comment]
스와이프 제스처 예제 : https://moonibot.tistory.com/54?category=823807
