### ISSUE TITLE
04-2. 리스트탭: 검색기능 - 제목만 검색되도록 설정

### ISSUE THREAD

**Issue by jbeexxx** [ProjectInTheClass/mogrige#70]
전체 텍스트 검색에 걸리게 하지 않고 제목만 필터 할 수있도록 설정

**Comment by thyomoon** [comment]
데이터 구조를 살짝 수정했습니다(모델에 keywords("keyword01, keyword02, keyword03)추가) 
지금은 테이블 뷰에서 제목이 해시태그 형으로 보이지 않는데 해시태그로 보여야 한다면 keywords의 모델을 수정해야 할 것 같습니다!

**Comment by jbeexxx** [comment]
해시태그로 안보이는 것이 더 좋을 것 같습니다.

**Comment by thyomoon** [comment]
감사합니다. 그럼 현버전 유지하는 형태로 이슈 클로즈 하겠습니다!
